spring:
  application:
    name: ApiBoleto
  datasource:
    url: jdbc:mysql://buscasaudeapi.mysql.database.azure.com:3306/apiboleto?createDatabaseIfNotExist=true
    username: buscasaudeapi
    password: Gouvea@2000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

santander:
  api:
    base-url: https://trust-open.api.santander.com.br
    auth-url: https://trust-open.api.santander.com.br/auth/oauth/v2/token
    workspace-id: ${SANTANDER_WORKSPACE_ID:bae92e16-7428-41e9-b500-eb805190eecb}
    client-id: ${SANTANDER_CLIENT_ID:dp4OJyTcMHU9HAD0zl7dQzJGxxTpplBI}
    client-secret: ${SANTANDER_CLIENT_SECRET:xFARqMD3XvbKPaC5}
  certificate:
    path: ${SANTANDER_CERT_PATH:classpath:certificates/client.p12}
    password: ${SANTANDER_CERT_PASSWORD:sssantander}
    type: PKCS12
